# Generated by Django 2.2.1 on 2019-06-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalfortress', '0003_auto_20190608_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currRound',
            field=models.IntegerField(default=0),
        ),
    ]
